### ISSUE TITLE
Hide module parameters in elaboration

### ISSUE THREAD

**Issue by astump** [cedille/cedille#120]
A recent change -- I am guessing Colin's modification of classify functions to be elaborating -- has made it so that module parameters show up in expressions in the context and inspect buffers.  This is really distracting, and we should try to hide them there.  Not quite sure what that will entail!

**Comment by HerbertMcSnout** [comment]
I think the problem was that in src/to-string.agda, the drop-mod-args-type function told the ctxt-qualif-args-length to count the number of NotErased arguments (i.e. regular term ones) and remove that many module arguments from the type variable. This was a typo and should have only happened for terms when erase-types option is on.

**Comment by astump** [comment]
Thanks, Colin, for fixing that.  Also for the pointer to where this
operation is happening.  I can confirm that your fix is working for the
test cases I have -- and making my code much easier to follow now!  Thanks
again, Aaron
