### ISSUE TITLE
Add support for macOS install paths

### ISSUE THREAD

**Issue by zmthy** [cedille/cedille#130]
I have opened a PR for a Homebrew formula to install Cedille: https://github.com/Homebrew/homebrew-core/pull/45647. The formula currently has to symlink installed binaries into the emacs-lisp directory to ensure that setting `cedille-path` works. Adding support for these paths would make the formula simpler and ensure that it works out of the box without having to set `cedille-path` at all. I have a corresponding code change for cedille-mode if you're happy to standardise on this Homebrew formula as the standard macOS installation.

**Comment by amarmaduke** [comment]
Hey zmthy,

Thanks for all your work on making a brew formula for Cedille!

I don't know a lot about brew, unfortunately, so I'll need some time to look into it to figure out if we're happy with this formula. I'll get back to you once I know a little bit more

**Comment by amarmaduke** [comment]
Hey again @zmthy  I understand how brew handles packages better now and think what you've done is perfectly standard. My guess is the problem with `cedille-mode` not finding the `cedille` binary is because, for macos, a lot of the system specific data is just `nil`

If you already have proposed changes please go ahead and create a PR and I'll review it. Thanks again for helping out!

**Comment by amarmaduke** [comment]
@zmthy One last thing to note: We have a developer meeting this coming Monday, I imagine it would be better for the brew formula if we have a new point release (1.1.2), so I'll bring that up. Regardless we'll try to figure something out so that the sysmlinks in the brew formula can be removed.

**Comment by zmthy** [comment]
Excellent, I was just going to ask about that. I think the formula is not likely to get merged until it can target a stable release with this change.

**Comment by amarmaduke** [comment]
@zmthy Sorry I forgot about another important thing to mention: You may want to use `make cedille-mac` instead of just `make` as the later will build everything with dynamic linking and the former will statically link everything but system libraries (which will be dynamically linked). This will only matter if the people at brew decide to distribute a cedille binary instead of building from source but its a small bit of future proofing.
