### ISSUE TITLE
Reverse Synthesizing Rho Rewrite Direction (and Cedille Core rho as well)

### ISSUE THREAD

**Issue by HerbertMcSnout** [cedille/cedille#33]
Reverse rewriting direction of rho in a synthesizing position to right-to-left, and reverse Cedille Core rho rewrite direction for consistency.

**Comment by cwjnkins** [comment]
To add some documentation for the reasoning for this: we would like, as much as possible, for the following type inference rule to hold (commonly called "subsumption" in bidirectional type systems)

    Γ ⊢ t ⇒ T
    —————————
    Γ ⊢ t ⇐ T

That is, any term that can synthesize a type can be checked against the same type (maybe after conversion checking). Currently, `ρ` poses a bit of an issue for this, since rewriting left-to-right in both the synthesizing and checking case does not lead to convertible types. Adding this change helps to (but does not fully) achieve this.
