### ISSUE TITLE
Lack of term meta-variable matching in type inference prevents elaborating modules with term parameters

### ISSUE THREAD

**Issue by HerbertMcSnout** [cedille/cedille#73]
Below, both myfun1 and myfun3 type-check but myfun2 does not ("The expected argument type is not a (first-order) match of the computed type"). The only difference between them is Sigma1 has a type parameter, Sigma2 a term one, and Sigma3 has none; this eventually causes issues when elaborating a file or datatype with term parameters. Is this intended behavior, or could it be a bug @cwjnkins?  

`Sigma1 : Π X123 : ★. Π A : ★. (A ➔ ★) ➔ ★ =`
`  λ X123 : ★. λ A : ★. λ B : A ➔ ★. ∀ X : ★. (Π a : A. B a ➔ X) ➔ X.`
`pair1 : ∀ X123 : ★. ∀ A : ★. ∀ B : A ➔ ★. Π a : A. B a ➔ Sigma1 · X123 · A · B = Λ x123. Λ A. Λ B. λ a. λ b. Λ X. λ f. f a b.`

`Sigma2 : Π x123 : {λ x. x ≃ λ x. x}. Π A : ★. (A ➔ ★) ➔ ★ =`
`  λ x123 : {λ x. x ≃ λ x. x}. λ A : ★. λ B : A ➔ ★. ∀ X : ★. (Π a : A. B a ➔ X) ➔ X.`
`pair2 : Π x123 : {λ x. x ≃ λ x. x}. ∀ A : ★. ∀ B : A ➔ ★. Π a : A. B a ➔ Sigma2 x123 · A · B = λ x123. Λ A. Λ B. λ a. λ b. Λ X. λ f. f a b.`

`Sigma3 : Π A : ★. (A ➔ ★) ➔ ★ =`
`  λ A : ★. λ B : A ➔ ★. ∀ X : ★. (Π a : A. B a ➔ X) ➔ X.`
`pair3 : ∀ A : ★. ∀ B : A ➔ ★. Π a : A. B a ➔ Sigma3 · A · B = Λ A. Λ B. λ a. λ b. Λ X. λ f. f a b.`

`myfun1 : ∀ X123 : ★. ∀ X : ★. Π x : X. {x ≃ λ x. x} ➔ Sigma1 · X123 · X · (λ x : X. {x ≃ λ x. x}) =`
`  Λ X123. Λ X. λ x. λ e. pair1 · X123 x e.`

`myfun2 : Π x123 : {λ x. x ≃ λ x. x}. ∀ X : ★. Π x : X. {x ≃ λ x. x} ➔ Sigma2 x123 · X · (λ x : X. {x ≃ λ x. x}) =`
`  λ x123. Λ X. λ x. λ e. pair2 x123 x e.`

`myfun3 : ∀ X : ★. Π x : X. {x ≃ λ x. x} ➔ Sigma3 · X · (λ x : X. {x ≃ λ x. x}) =`
`  Λ X. λ x. λ e. pair3 x e.`

**Comment by cwjnkins** [comment]
This appears to be a bug. While we don't try very hard to make higher-order matches, we are able to make some very easy ones, such as with `myfun1` and `myfun3`. For `myfun2`, the following (contextual) prototype and head type should be able to match no problem

    prototype: ? ➔                                                          ? ➔       ? ➔   Sigma2 x123 · X · (λ x : X. {x ≃ λ x. x})
    head:      Π x123 : { λ x' . x' ≃ λ x' . x' } . ∀ A : ★ . ∀ B : A ➔ ★ . Π a : A . B a ➔ Sigma2 x123 · A · B

I suspect something is getting unfolded behind the scenes somewhere during type inference, preventing this easy match.

Also, after looking through the other examples, I spotted another bug: the span for `pair1 · X123` has type

    ∀ A : ★ . ∀ B : X ➔ ★ . Π a : A . B a ➔ Sigma1 · X123 · A · B

`B` has been given the wrong kind. Technically this shouldn't cause unsoundness because `A` has already been matched to `X` -- but it should be showing the original type, and not the match decorations.

I'll take a look at both of these today.

**Comment by cwjnkins** [comment]
@HerbertMcSnout 

My guess was wrong. After doing more digging, I finally came upon the cause of this issue:

    ([Sigma2 x123' · A · B] ‼ Sigma2 x123 · X · (λ x' : X . { x' ≃ λ x'' . x'' }))

In brackets is the return type with variables `x123` `A` and `B` bound by quantifiers in the type of `myfun2`, and to the right of the !! is the contextual type. The problem is that we do not perform any term matching, so we fail when comparing term meta-variable `x123'` with `x123`.

This is a pretty nasty issue when it interacts with module parameters: definitions within a module with term parameters won't have these term meta-variables in their types which will allow them to be *checked*, but the elaborations will have to have the types of some subexpressions synthesize instead!

It's a bit of a hack, but since I don't think we should wait for proper term matching to be implemented before we can elaborated expressions with module parameters, my proposal is that I add support for the special case of matching term meta-variables to term meta-variables. That wouldn't negatively affect elaboration of modules with *instantiated* parameters, correct?

**Comment by cwjnkins** [comment]
Actually, perhaps an even quicker workaround would be to expand module parameter like so:

    myfun2 : Π x123 : {λ x. x ≃ λ x. x}. ∀ X : ★. Π x : X. {x ≃ λ x. x} ➔ Sigma2 x123 · X · (λ x : X. {x ≃ λ x. x}) =
    λ x123. Λ X. λ x. λ e. (χ - pair2 x123) x e.

Type inference will treat `(χ - pair2 x123)` as a spine head and synthesize its type. Then, the very same contextual match performed in the module will occur for the parameter expanded definitions. What do you think?

**Comment by astump** [comment]
Thanks for digging into this, Colin.  Let's make sure to go through in 
detail Monday.
Aaron

**Comment by HerbertMcSnout** [comment]
Qualifying variables like `pair2` to `(χ - pair2 x123)` (with `x123` being some term module parameter) should be an easy hack for now—great idea!
