### ISSUE TITLE
Some elaborations to Cedille Core seem not to be checking

### ISSUE THREAD

**Issue by astump** [cedille/cedille#92]
I am trying to elaborate new-lib/data/sum.ced to Cedille Core and check it (within emacs using Alt-s on the .cdle file).  This is failing for me at present on master.  

I am also adding an issue to request CI testing of new-lib...

**Comment by HerbertMcSnout** [comment]
So somewhat amusingly, the problem is in parsing the module name: "data**/**sum". I could enable parsing of this in Cedille Core, but I think the default should be to change Cedille (in this case, the elaborator) first if possible. So I'll just refactor the module name, as is done for all binders and variables.
